### ISSUE TITLE
Running problems 

### ISSUE THREAD

**Issue by wgao11** [friendly/SAS-macros#1]
Dear Michael,

Many thanks for contributing this macro. I am a researcher working at King's College London. I've tried to use your macro to assess the collinearity issues of several categorical variables in logistic regression, However, I keep on getting the error info as below (in quote), can you please help? 

Thanks in advance. 
Best,

Gao

"
NOTE: IML Ready
ERROR: Operand _varname does not have a value.

 statement : READ at line 9202 column 1
NOTE: Exiting IML.
NOTE: The SAS System stopped processing this step because of errors.
NOTE: PROCEDURE IML used (Total process time):
      real time           0.01 seconds
      cpu time            0.01 seconds

ERROR: File WORK.FINAL2.DATA does not exist.

NOTE: The SAS System stopped processing this step because of errors.
NOTE: PROCEDURE PRINT used (Total process time):
      real time           0.01 seconds
      cpu time            0.01 seconds

"

**Comment by friendly** [comment]
I have no idea what macro you are referring to nor what you tried. Can  you provide a minimal
example of your data and code?

**Comment by wgao11** [comment]
Thanks Michael. This is the macro "SAS-macros/collin.sas". The dummy data is pasted as below. Basically I mode var8 based on var1-var7, I would like to assess the collinearity between var1-var7. As you will see, var1-var7 is a mixture of numerical and string variables. Thanks for your help. 

var1    var2    var3    var4    var5    var6    var7    var8
0   1   e   1   1   U   Ch  1
1   2   b   2   5   U   Ch  0
4   1   b   0   2   U   Ch  0
5   1   h   0   3   U   Ch  0
4   2   a   1   4   U   Ch  0
2   2   a   0   1   U   Ch  1
4   2   g   1   2   U   Ch  1
5   1   e   1   1   U   Ch  0
0   2   l   0   2   U   Ch  1
6   2   n   1   1   U   Ch  0
0   1   a   0   5   U   Ch  1
3   2   a   2   5   U   Ch  1
0   2   g   0   4   U   Ch  0
3   2   o   1   3   U   Ch  0
4   1   a   1   1   U   Ch  0
2   1   e   0   1   U   Ch  1
1   2   h   1   1   U   Ch  1
2   1   h   1   1   U   Ch  1
0   2   g   0   2   U   Ch  0
1   1   g   2   5   U   Ch  0
1   1   a   0   1   U   Ch  0
0   2   h   0   1   U   Ch  1
4   1   e   2   2   U   Ch  0
4   1   a   1   1   U   Ch  0
5   1   i   1   5   U   Ch  1
4   1   b   1   5   U   Ch  0
5   1   n   0   2   U   Ch  0
0   1   g   2   1   U   Ch  0
5   1   n   1   4   R   Ch  1
5   2   e   4   2   U   Ch  0
3   2   h   1   5   U   Ch  1
3   1   e   2   1   U   Ch  0
0   2   n   0   1   U   Ch  0
4   1   g   1   5   U   Ch  0
1   1   g   1   4   U   Ch  1
4   1   e   0   1   U   Ch  0
0   1   l   0   4   U   Ch  0
2   1   g   0   4   U   Ch  0
3   1   a   1   4   U   Ch  0
2   1   a   2   4   U   Ch  0
0   1   g   0   1   U   Ch  1
5   2   g   0   2   U   Ch  1
5   2   p   1   4   U   Ch  0
0   2   k   1   3   U   Ch  1
1   1   j   1   1   U   Ch  1
6   1   a   2   1   U   Ch  0
0   1   p   2   1   U   Ch  0
3   1   a   1   5   U   Ch  1
1   2   j   0   3   U   Ch  0
3   1   o   1   3   U   Ch  0
5   1   g   0   1   U   Ch  1
3   1   p   2   2   U   Ch  0
2   1   n   0   2   U   Ch  1
5   2   l   0   5   U   Ch  1
1   1   g   0   2   U   Ch  1
4   1   a   0   5   U   Ch  0
5   1   n   1   4   U   Ch  0
3   1   g   1   2   U   Ch  1
0   1   k   2   2   U   Ch  0
6   1   i   0   3   U   Ch  1
0   2   g   1   2   U   Ch  0
4   2   i   0   5   R   Ch  1
3   2   d   2   4   U   Ch  0
3   1   g   2   1   U   Ch  0
1   2   a   0   3   U   Ch  1
2   1   a   0   1   U   Ch  0
6   1   n   1   5   U   Ch  1
0   1   g   0   2   U   Ch  1
6   1   n   0   2   U   Ch  0
1   2   l   0   4   U   Ch  1
1   2   e   0   1   U   Ch  1
2   1   a   1   5   U   Ch  1
4   1   p   2   1   U   Ch  0
0   1   l   1   1   U   Ch  0
3   2   a   0   5   U   Ch  1
4   1   n   2   4   U   Ch  1
6   1   a   1   1   U   Ch  0
5   2   a   1   4   U   Ch  0
3   1   o   3   4   U   Ch  0
2   2   g   0   2   U   Ch  0
3   1   g   2   5   R   Ch  0
3   2   p   2   3   U   Ch  0
1   1   p   1   1   U   Ch  0
2   1   g   0   1   U   Ch  0
3   2   l   1   5   U   Ch  0
3   1   n   3   2   U   Ch  0
5   1   n   0   5   U   Ch  0
6   2   n   1   1   U   Ch  1
0   1   l   0   3   U   Ch  1
5   2   a   1   5   U   Ch  0
5   1   g   1   2   U   Ch  0
5   1   c   0   2   U   Ch  1
3   2   j   1   2   U   Ch  1
5   2   n   0   4   U   Ch  0
4   2   g   0   5   U   Ch  1
4   1   h   0   5   U   Ch  1
4   2   d   0   5   U   Ch  0
5   1   n   1   3   U   Ch  1
4   1   j   0   4   R   Ch  1
5   1   i   1   2   U   Ch  1

**Comment by friendly** [comment]
This is not a macro that I wrote or maintain.  It just happens to be in my macro collection.

However,  I believe the problem is that it does not support character variables, because collinearity diagnostics are based on the covariance matrix of the predictors.

**Comment by wgao11** [comment]
I see. Many thanks!
